package:
  name: eukulele
  version: 2.0.7

build:
  noarch: python

source:
  path: ../

requirements:
  build:
    - python >=3.6
    - numpy
    - biopython ==1.77
    - pandas
    - seaborn
    - chardet
    - argparse
    - multiprocess
    - joblib
    - ujson
    - pyyaml
    - yaml
    - matplotlib
    - pytest-runner   
    - python-coveralls
    - pytest-cov
    - pytest-xdist
    - blast
    - diamond 
    - transdecoder
    - wget

  run:
    - python >=3.6
    - numpy
    - biopython
    - pandas
    - seaborn
    - chardet
    - argparse
    - multiprocess
    - joblib
    - ujson
    - pyyaml
    - yaml
    - matplotlib
    - pytest-runner
    - python-coveralls
    - pytest-cov
    - pytest-xdist
    - blast 
    - diamond 
    - transdecoder
    - wget

about:
  home: https://github.com/AlexanderLabWHOI/EUKulele
  license: MIT
  license_file: LICENSE
  summary: Easy taxonomic annotation for eukaryotic microbes
