package:
  name: eukulele
  version: 2.0.0

build:
  noarch: python

source:
  path: ../

requirements:
  build:
    - python>=3.6
    - numpy
    - biopython==1.77
    - pandas
    - seaborn
    - chardet
    - argparse
    - multiprocess
    - joblib
    - ujson
    - pyyaml
    - yaml
    - matplotlib
    - pytest-runner   
    - python-coveralls
    - pytest-cov
    - pytest-xdist 

    - blast 
#    - busco==4.1.4
    - diamond 
    - transdecoder

  run:
    - python>=3.6
    - numpy
    - biopython
    - pandas
    - seaborn
    - chardet
    - argparse
    - multiprocess
    - joblib
    - ujson
    - pyyaml
    - yaml
    - matplotlib
    - pytest-runner
    - python-coveralls
    - pytest-cov
    - pytest-xdist
    - blast 
 #   - busco==4.0.6 
    - diamond 
    - transdecoder

about:
  home: https://github.com/AlexanderLabWHOI/EUKulele
  license: MIT
  license_file: LICENSE
  summary: Easy taxonomic annotation for eukaryotic microbes
