jobname: test 
mets_or_mags: METs #answer METs or MAGs
nucleotide_extension: .fna
protein_extension: .faa
scratch: /vortexfs1/scratch/halexander/EUKULELE
reference: /vortexfs1/omics/alexander/data/mmetsp/reference_dir
database: /vortexfs1/omics/alexander/data/mmetsp/reference_dir
output: first-test/ 
samples: test-samples/
ref_fasta: reference-pep.fa # amino acid sequences
ref_tax: taxonomy-table.txt
ref_prot: protein-species-map.json 
cutoff: tax-cutoffs.yaml 
taxonomy_table: /vortexfs1/omics/alexander/data/mmetsp/taxonomy_v2.txt #path to eukulele taxonomy table
alignment-choice: diamond #diamond or blast
transdecoder_orfsize: 100
