metaT: False
MAGs: True
scratch: /vortexfs1/scratch/halexander/EUKULELE
reference: /vortexfs1/omics/alexander/data/mmetsp/reference_dir
ref_fasta: reference-pep.fa
ref_tax: taxonomy-table.txt
ref_prot: protein-species-map.json 
cutoff: tax-cutoffs.yaml 
taxonomy_table: /vortexfs1/omics/alexander/data/mmetsp/taxonomy_v2.txt
alignment-choice: diamond #or blast? or ... (allow people to choose what kind of alignment they want to run)
