jobname: wap 
mets_or_mags: METs # answer METs or MAGs
nucleotide_extension: .fasta
protein_extension: .faa
scratch: /vortexfs1/scratch/akrinos/EUKULELE
use_salmon_counts: 1 # if this is set to 1, names_to_reads is used
salmon_dir: ../testoutput/salmon_indiv
names_to_reads: namestoreads.csv # if this file exists in the reference directory (below), this file is used
reference: /vortexfs1/omics/alexander/akrinos/EUKulele-Reference
database: /vortexfs1/omics/alexander/akrinos/EUKulele-Reference
#reference: /vortexfs1/omics/alexander/data/mmetsp/reference_dir
#database: /vortexfs1/omics/alexander/data/mmetsp/reference_dir
output: ../EUKulele_output_WAP_PhyloDB_counts
samples: samples #/vortexfs1/omics/saito/BATS2019-clio-metaT/eukrhythmic_output/merged 
ref_fasta: tax-tables/phylodb.pep.fa #reference-pep.fa # amino acid sequences
ref_tax: tax-table-phylodb.txt #taxonomy-table.txt
ref_prot: protein-map-phylodb.json #protein-species-map.json 
cutoff: tax-cutoffs.yaml 
consensus_cutoff: 0.75
taxonomy_table: /vortexfs1/omics/alexander/data/mmetsp/taxonomy_v2.txt #path to eukulele taxonomy table
alignment_choice: diamond # diamond or blast
choose_parallel: parallel # parallel or series; whether to run estimate taxonomy in parallel mode (Requires joblib & multiprocessing)
transdecoder_orfsize: 100
