jobname: wap
metaT: True
MAGs: True
scratch: /vortexfs1/scratch/akrinos/EUKULELE
reference: /vortexfs1/omics/alexander/data/mmetsp/reference_dir
output: ../EUKulele_output_WAP_18June
samples: samples
ref_fasta: reference-pep.fa # amino acid sequences
ref_tax: taxonomy-table.txt
ref_prot: protein-species-map.json 
cutoff: tax-cutoffs.yaml 
consensus_cutoff: 0.75
taxonomy_table: /vortexfs1/omics/alexander/data/mmetsp/taxonomy_v2.txt
alignment-choice: diamond #diamond or blast? or ... (allow people to choose what kind of alignment they want to run)
