jobname: wap 
mets_or_mags: METs # answer METs or MAGs
nucleotide_extension: .fasta
protein_extension: .faa
scratch: /vortexfs1/scratch/akrinos/EUKULELE
use_salmon_counts: 1 # if this is set to 1, names_to_reads is used
salmon_dir: ../WAP_out/salmon_by_assembly_group #../testoutput/salmon_indiv
names_to_reads: namestoreads_WAP_2July2020.csv # if this file exists in the reference directory (below), this file is used
reference: /vortexfs1/omics/alexander/akrinos/EUKulele-Reference #/vortexfs1/omics/alexander/data/euk-prot-db/proteins #/vortexfs1/omics/alexander/akrinos/EUKulele-Reference
database: /vortexfs1/omics/alexander/akrinos/EUKulele-Reference #/vortexfs1/omics/alexander/data/euk-prot-db #/vortexfs1/omics/alexander/akrinos/EUKulele-Reference
#reference: /vortexfs1/omics/alexander/data/mmetsp/reference_dir
#database: /vortexfs1/omics/alexander/data/mmetsp/reference_dir
output: ../EUKulele_output_WAP_PhyloDB_counts_busco #../EUKulele_output_WAP_EukProt_counts #PhyloDB_counts
samples: /vortexfs1/omics/alexander/akrinos/WAP_out/cluster_by_assembly_group #samples #/vortexfs1/omics/saito/BATS2019-clio-metaT/eukrhythmic_output/merged 
ref_fasta: phylodb_1.076.pep.fa #/vortexfs1/omics/alexander/data/euk-prot-db/proteins #reference-pep.fa  #phylodb.pep.fa #reference-pep.fa # amino acid sequences

# Path for reference taxonomy table and protein JSON file should be relative to reference entry above.
# You create both of these previously using the EUKulele-Reference/ directory.
ref_tax: tax-table-phylodb.txt #../tax-table-formatted.txt #tax-table-phylodb.txt #taxonomy-table.txt
ref_prot: protein-map-phylodb.json #../protein-map.json #protein-map-phylodb.json #protein-species-map.json 

cutoff: tax-cutoffs.yaml 
consensus_cutoff: 0.75
alignment_choice: diamond # diamond or blast
choose_parallel: parallel # parallel or series; whether to run estimate taxonomy in parallel mode (Requires joblib & multiprocessing)
transdecoder_orfsize: 100
