jobname: test 
mets_or_mags: METs #answer METs or MAGs
nucleotide_extension: .fna
protein_extension: .faa
scratch: /vortexfs1/scratch/halexander/EUKULELE
reference: /vortexfs1/omics/alexander/data/mmetsp/reference_dir
output: ../EUKulele_output_WAP_18June
samples: samples
ref_fasta: reference-pep.fa # amino acid sequences
ref_tax: taxonomy-table.txt
ref_prot: protein-species-map.json 
cutoff: tax-cutoffs.yaml 
consensus_cutoff: 0.75
taxonomy_table: /vortexfs1/omics/alexander/data/mmetsp/taxonomy_v2.txt #path to eukulele taxonomy table
alignment_choice: diamond # diamond or blast
choose_parallel: parallel # parallel or series; whether to run estimate taxonomy in parallel mode (Requires joblib & multiprocessing)
transdecoder_orfsize: 100
